USE Food_Manager
CREATE TABLE Customer(
			cid VARCHAR(10) NOT NULL UNIQUE,
			cname VARCHAR(30) NOT NULL,
			cphone VARCHAR(15) NOT NULL,
			caddr VARCHAR(50) NOT NULL,
			aid VARCHAR(10) NOT NULL,
			PRIMARY KEY(cid),
			FOREIGN KEY (aid) REFERENCES Account ON DELETE NO ACTION);