USE waimai;
CREATE TABLE Food(
			fid VARCHAR(10) NOT NULL UNIQUE,
			price FLOAT(5) NOT NULL,
			fname VARCHAR(30) NOT NULL,
			rid VARCHAR(10) NOT NULL,
			PRIMARY KEY(fid),
			FOREIGN KEY (rid) REFERENCES Restaurant ON DELETE NO ACTION);